# Generated by Django 2.2.6 on 2019-11-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
